services:
  - type: web
    name: lyfind-notifications
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
